services:
  jenkins:
    image: jenkins/jenkins:lts  # Dùng image Jenkins LTS
    container_name: jenkins
    ports:
      - "8080:8080"   # Cổng web Jenkins
      - "50000:50000" # Dùng cho Jenkins Agent
    build:
      context: .  # Sử dụng Dockerfile từ thư mục hiện tại
      dockerfile: Dockerfile
    volumes:
      - ./jenkins_home:/var/jenkins_home  # Lưu trữ dữ liệu Jenkins
      - /var/run/docker.sock:/var/run/docker.sock # Cho phép Jenkins quản lý Docker
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false # Bỏ qua wizard setup

  ansible:
    image: williamyeh/ansible:alpine3
    container_name: ansible
    volumes:
      - ./ansible:/ansible  # Mount thư mục Ansible vào container
    working_dir: /ansible
    entrypoint: ["/bin/sh", "-c", "while true; do sleep 30; done;"]  # Giữ container chạy
